### ISSUE TITLE
Create mysql procedure for adding elements

### ISSUE THREAD

**Issue by Andreassim** [MathiasReker/WishShare#49]
When adding elements a procedure that returns the primary key of the newly created entry

**Comment by Moshizzl3** [comment]
https://stackoverflow.com/questions/16481926/output-last-inserted-primary-key-value-from-stored-procedure

**Comment by Andreassim** [comment]
this is simpler https://stackoverflow.com/questions/14234257/java-with-sql-the-return-value-of-insert-command
